# Generated by Django 5.1.4 on 2024-12-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_staff',
            field=models.BooleanField(default=True, editable=False, verbose_name='is staff'),
        ),
    ]
