# Generated by Django 5.1.4 on 2024-12-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_superuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='commonuser',
            options={'verbose_name': 'common user', 'verbose_name_plural': 'common users'},
        ),
        migrations.AlterModelOptions(
            name='doctoruser',
            options={'verbose_name': 'doctor user', 'verbose_name_plural': 'doctor users'},
        ),
        migrations.AlterModelOptions(
            name='superuser',
            options={'verbose_name': 'super user', 'verbose_name_plural': 'super users'},
        ),
    ]
